import { defineEnableDraftMode } from "next-sanity/draft-mode";

import { isSanityConfigured, readToken } from "@/sanity/env";
import { client } from "@/sanity/lib/client";

/**
 * Enables Next.js Draft Mode for Sanity previews. The Presentation tool (and
 * preview links generated by Studio) call this route with a signed secret,
 * which `defineEnableDraftMode` verifies against the Content Lake using the
 * server-side read token. Without Sanity configured, previews are refused.
 */
const handler = isSanityConfigured
  ? defineEnableDraftMode({
      client: client.withConfig({ token: readToken() }),
    })
  : {
      GET: async () =>
        new Response(
          "Draft previews require a configured Sanity project. See README → Sanity setup.",
          {
            status: 503,
          },
        ),
    };

export const { GET } = handler;
