/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CaseStudyMedia = {
  _type: "caseStudyMedia";
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  alt?: string;
  caption?: string;
  aspect?: "square" | "16:9";
};

export type CaseStudy = {
  _type: "caseStudy";
  slug?: Slug;
  title?: string;
  subtitle?: string;
  displayDate?: string;
  shortDescription?: string;
  body?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  externalUrl?: string;
  heroImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  gallery?: Array<
    {
      _key: string;
    } & CaseStudyMedia
  >;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Engagement = {
  _type: "engagement";
  startYear?:
    | 2027
    | 2026
    | 2025
    | 2024
    | 2023
    | 2022
    | 2021
    | 2020
    | 2019
    | 2018
    | 2017
    | 2016
    | 2015
    | 2014
    | 2013
    | 2012
    | 2011
    | 2010
    | 2009
    | 2008
    | 2007
    | 2006
    | 2005
    | 2004
    | 2003
    | 2002
    | 2001
    | 2000
    | 1999
    | 1998
    | 1997
    | 1996
    | 1995;
  endYear?:
    | 2027
    | 2026
    | 2025
    | 2024
    | 2023
    | 2022
    | 2021
    | 2020
    | 2019
    | 2018
    | 2017
    | 2016
    | 2015
    | 2014
    | 2013
    | 2012
    | 2011
    | 2010
    | 2009
    | 2008
    | 2007
    | 2006
    | 2005
    | 2004
    | 2003
    | 2002
    | 2001
    | 2000
    | 1999
    | 1998
    | 1997
    | 1996
    | 1995;
  tags?: Array<string>;
  label?: string;
  description?: string;
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type Client = {
  _id: string;
  _type: "client";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  logoAspect?: number;
  logoTreatment?: {
    scale?: number;
    padding?: number;
    alignment?: "center" | "start" | "end";
    logoLight?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    logoDark?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
    compactLogo?: {
      asset?: SanityFileAssetReference;
      media?: unknown;
      _type: "file";
    };
  };
  description?: string;
  hidden?: boolean;
  engagements?: Array<
    {
      _key: string;
    } & Engagement
  >;
  caseStudy?: CaseStudy;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: string;
  logo?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  contactUrl?: string;
  linkedinUrl?: string;
  navigation?: Array<{
    label?: string;
    href?: string;
    available?: boolean;
    _key: string;
  }>;
  workStartYear?: number;
  workEndYear?: number;
  seoTitle?: string;
  seoDescription?: string;
  defaultOgImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  favicon?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | CaseStudyMedia
  | CaseStudy
  | Engagement
  | SanityFileAssetReference
  | Client
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{  title,  description,  "logoUrl": logo.asset->url,  contactUrl,  linkedinUrl,  navigation[]{ label, href, available },  workStartYear,  workEndYear,  seoTitle,  seoDescription,  defaultOgImage,  "faviconUrl": favicon.asset->url}
export type SITE_SETTINGS_QUERY_RESULT = {
  title: string | null;
  description: string | null;
  logoUrl: string | null;
  contactUrl: string | null;
  linkedinUrl: string | null;
  navigation: Array<{
    label: string | null;
    href: string | null;
    available: boolean | null;
  }> | null;
  workStartYear: number | null;
  workEndYear: number | null;
  seoTitle: string | null;
  seoDescription: string | null;
  defaultOgImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  faviconUrl: string | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: WORK_INDEX_QUERY
// Query: *[_type == "client" && hidden != true] | order(name asc){  "id": _id,  name,  "slug": slug.current,  "logoUrl": logo.asset->url,  logoAspect,  logoTreatment{    scale,    padding,    alignment,    "lightUrl": logoLight.asset->url,    "darkUrl": logoDark.asset->url,    "compactUrl": compactLogo.asset->url  },  description,  engagements[]{ startYear, endYear, tags, description },  caseStudy{    "slug": slug.current,    title,    heroImage  }}
export type WORK_INDEX_QUERY_RESULT = Array<{
  id: string;
  name: string | null;
  slug: string | null;
  logoUrl: string | null;
  logoAspect: number | null;
  logoTreatment: {
    scale: number | null;
    padding: number | null;
    alignment: "center" | "end" | "start" | null;
    lightUrl: string | null;
    darkUrl: string | null;
    compactUrl: string | null;
  } | null;
  description: string | null;
  engagements: Array<{
    startYear:
      | 1995
      | 1996
      | 1997
      | 1998
      | 1999
      | 2000
      | 2001
      | 2002
      | 2003
      | 2004
      | 2005
      | 2006
      | 2007
      | 2008
      | 2009
      | 2010
      | 2011
      | 2012
      | 2013
      | 2014
      | 2015
      | 2016
      | 2017
      | 2018
      | 2019
      | 2020
      | 2021
      | 2022
      | 2023
      | 2024
      | 2025
      | 2026
      | 2027
      | null;
    endYear:
      | 1995
      | 1996
      | 1997
      | 1998
      | 1999
      | 2000
      | 2001
      | 2002
      | 2003
      | 2004
      | 2005
      | 2006
      | 2007
      | 2008
      | 2009
      | 2010
      | 2011
      | 2012
      | 2013
      | 2014
      | 2015
      | 2016
      | 2017
      | 2018
      | 2019
      | 2020
      | 2021
      | 2022
      | 2023
      | 2024
      | 2025
      | 2026
      | 2027
      | null;
    tags: Array<string> | null;
    description: string | null;
  }> | null;
  caseStudy: {
    slug: string | null;
    title: string | null;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
    } | null;
  } | null;
}>;

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDY_QUERY
// Query: *[_type == "client" && caseStudy.slug.current == $slug && hidden != true][0]{  "clientId": _id,  "clientName": name,  "logoUrl": logo.asset->url,  engagements[]{ startYear, endYear, tags },  caseStudy{    "slug": slug.current,    title,    subtitle,    displayDate,    shortDescription,    body,    externalUrl,    heroImage{ ..., "dimensions": asset->metadata.dimensions, "lqip": asset->metadata.lqip },    gallery[]{ _key, image{ ..., "dimensions": asset->metadata.dimensions, "lqip": asset->metadata.lqip }, alt, caption, aspect },    seoTitle,    seoDescription,    ogImage  }}
export type CASE_STUDY_QUERY_RESULT = {
  clientId: string;
  clientName: string | null;
  logoUrl: string | null;
  engagements: Array<{
    startYear:
      | 1995
      | 1996
      | 1997
      | 1998
      | 1999
      | 2000
      | 2001
      | 2002
      | 2003
      | 2004
      | 2005
      | 2006
      | 2007
      | 2008
      | 2009
      | 2010
      | 2011
      | 2012
      | 2013
      | 2014
      | 2015
      | 2016
      | 2017
      | 2018
      | 2019
      | 2020
      | 2021
      | 2022
      | 2023
      | 2024
      | 2025
      | 2026
      | 2027
      | null;
    endYear:
      | 1995
      | 1996
      | 1997
      | 1998
      | 1999
      | 2000
      | 2001
      | 2002
      | 2003
      | 2004
      | 2005
      | 2006
      | 2007
      | 2008
      | 2009
      | 2010
      | 2011
      | 2012
      | 2013
      | 2014
      | 2015
      | 2016
      | 2017
      | 2018
      | 2019
      | 2020
      | 2021
      | 2022
      | 2023
      | 2024
      | 2025
      | 2026
      | 2027
      | null;
    tags: Array<string> | null;
  }> | null;
  caseStudy: {
    slug: string | null;
    title: string | null;
    subtitle: string | null;
    displayDate: string | null;
    shortDescription: string | null;
    body: Array<{
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal";
      listItem?: never;
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }> | null;
    externalUrl: string | null;
    heroImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      dimensions: SanityImageDimensions | null;
      lqip: string | null;
    } | null;
    gallery: Array<{
      _key: string;
      image: {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        dimensions: SanityImageDimensions | null;
        lqip: string | null;
      } | null;
      alt: string | null;
      caption: string | null;
      aspect: "16:9" | "square" | null;
    }> | null;
    seoTitle: string | null;
    seoDescription: string | null;
    ogImage: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
  } | null;
} | null;

// Source: src/sanity/lib/queries.ts
// Variable: CASE_STUDY_SLUGS_QUERY
// Query: *[_type == "client" && defined(caseStudy.slug.current) && hidden != true]{  "slug": caseStudy.slug.current,  "updatedAt": _updatedAt}
export type CASE_STUDY_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
  updatedAt: string;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '*[_type == "siteSettings"][0]{\n  title,\n  description,\n  "logoUrl": logo.asset->url,\n  contactUrl,\n  linkedinUrl,\n  navigation[]{ label, href, available },\n  workStartYear,\n  workEndYear,\n  seoTitle,\n  seoDescription,\n  defaultOgImage,\n  "faviconUrl": favicon.asset->url\n}': SITE_SETTINGS_QUERY_RESULT;
    '*[_type == "client" && hidden != true] | order(name asc){\n  "id": _id,\n  name,\n  "slug": slug.current,\n  "logoUrl": logo.asset->url,\n  logoAspect,\n  logoTreatment{\n    scale,\n    padding,\n    alignment,\n    "lightUrl": logoLight.asset->url,\n    "darkUrl": logoDark.asset->url,\n    "compactUrl": compactLogo.asset->url\n  },\n  description,\n  engagements[]{ startYear, endYear, tags, description },\n  caseStudy{\n    "slug": slug.current,\n    title,\n    heroImage\n  }\n}': WORK_INDEX_QUERY_RESULT;
    '*[_type == "client" && caseStudy.slug.current == $slug && hidden != true][0]{\n  "clientId": _id,\n  "clientName": name,\n  "logoUrl": logo.asset->url,\n  engagements[]{ startYear, endYear, tags },\n  caseStudy{\n    "slug": slug.current,\n    title,\n    subtitle,\n    displayDate,\n    shortDescription,\n    body,\n    externalUrl,\n    heroImage{ ..., "dimensions": asset->metadata.dimensions, "lqip": asset->metadata.lqip },\n    gallery[]{ _key, image{ ..., "dimensions": asset->metadata.dimensions, "lqip": asset->metadata.lqip }, alt, caption, aspect },\n    seoTitle,\n    seoDescription,\n    ogImage\n  }\n}': CASE_STUDY_QUERY_RESULT;
    '*[_type == "client" && defined(caseStudy.slug.current) && hidden != true]{\n  "slug": caseStudy.slug.current,\n  "updatedAt": _updatedAt\n}': CASE_STUDY_SLUGS_QUERY_RESULT;
  }
}
